#!/usr/bin/env bash
# script that will transfer a file to a server.
if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi

SRC=$1
IP=$2
UNAME=$3
DEST=$4

scp "$SRC" "$UNAME@$IP:$DEST"
