#!/usr/bin/env bash
# installs and configs nginx server
apt-get update
apt-get install nginx -y
DEST="/etc/nginx/sites-available"
printf "server  {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name localhost;
	root /home/ubuntu/;

	location / {
		index /index.html;	
	}
}" > "$DEST/default"
echo "Holberton School was here!" > index.html
nginx -s reload

