#!/usr/bin/env bash
# installs and configs nginx server
apt-get install nginx -y
DEST="/etc/nginx"
printf "server  {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name localhost;
	root html;

	location / {
		index /index.html;	
	}
}" > "$DEST/sites-available/default"
mkdir -p $DEST/html
echo "Holberton School was here!" > $DEST/html/index.html
service nginx stop
service nginx start
