#!/usr/bin/env bash
# adds a redirect location to server config
DEST="/etc/nginx"
sed -i "\$ilocation /redirect_me {\n return 301 "301 Moved Permanently";\n }" $DEST/sites-available/default
service nginx restart
