#!/usr/bin/env bash
# runs nginx as user nginx
sed -i '1cuser nginx;' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chmod o+r /etc/nginx/nginx.conf
pkill -f apache
sudo -u nginx nginx
